// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7RULrJ_aRwUvKeMV-TlpuKi2tXOkY6wA',
    appId: '1:267886855268:web:f5577b7a730aa239900b71',
    messagingSenderId: '267886855268',
    projectId: 'petit-63df1',
    authDomain: 'petit-63df1.firebaseapp.com',
    storageBucket: 'petit-63df1.firebasestorage.app',
    measurementId: 'G-5J191NZ6V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhxLg6HRuQNYYLoDxh-fSDui2Ed2p28IQ',
    appId: '1:267886855268:android:93dfa888823dcc25900b71',
    messagingSenderId: '267886855268',
    projectId: 'petit-63df1',
    storageBucket: 'petit-63df1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXdWTL1hp_LeBciLEKCEtucGQWwBDCaPc',
    appId: '1:267886855268:ios:7e8808e3a278f296900b71',
    messagingSenderId: '267886855268',
    projectId: 'petit-63df1',
    storageBucket: 'petit-63df1.firebasestorage.app',
    iosBundleId: 'com.example.petit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXdWTL1hp_LeBciLEKCEtucGQWwBDCaPc',
    appId: '1:267886855268:ios:7e8808e3a278f296900b71',
    messagingSenderId: '267886855268',
    projectId: 'petit-63df1',
    storageBucket: 'petit-63df1.firebasestorage.app',
    iosBundleId: 'com.example.petit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7RULrJ_aRwUvKeMV-TlpuKi2tXOkY6wA',
    appId: '1:267886855268:web:63b0d58e9eded7e5900b71',
    messagingSenderId: '267886855268',
    projectId: 'petit-63df1',
    authDomain: 'petit-63df1.firebaseapp.com',
    storageBucket: 'petit-63df1.firebasestorage.app',
    measurementId: 'G-KL6NDRE2YZ',
  );
}
